repos:
  - repo: local
    hooks:
      - id: Name check
        name: Check sensitive info
        verbose: true
        language: script
        entry: backend/pre_commit_hooks/rtx.sh
      - id: IP check
        name: Check sensitive info
        verbose: true
        language: script
        entry: backend/pre_commit_hooks/ip.sh
      - id: isort
        name: isort
        language: python
        types: [python]
        pass_filenames: false
        entry: isort --settings-path=backend/pyproject.toml .
      - id: black
        name: black
        language: python
        types: [python]
        pass_filenames: false
        entry: black --config=backend/pyproject.toml .
      # - id: flake8
      #   name: flak8
      #   language: python
      #   types: [python]
      #   pass_filenames: false
      #   entry: pflake8 --config=backend/pyproject.toml
